;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        beginning-of-buffer
        kill-visual-line
        mouse-set-region
        ))

(setq mc/cmds-to-run-once
      '(
        kill-visual-line
        ))
